# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false
format = '$username$shell$directory$git_branch$git_commit$git_status$nix_shell$jobs$line_break$status$character'

[shell]
disabled = false
fish_indicator = '󰈺'
bash_indicator = ''
zsh_indicator = '󰏰'
powershell_indicator = '󰨊'
nu_indicator = '󰞷'
style = 'white'

[directory]
read_only = ' 󰌾'
repo_root_style = 'bold bright-cyan'
style = 'cyan'
truncate_to_repo = false
truncation_length = 0

[git_branch]
format = '[\($branch\)]($style) '

[git_commit]
tag_disabled = false
tag_symbol = ' • '

[nix_shell]
format = '[$state(\($name\))]($style) '
pure_msg = ''
impure_msg = ''

[status]
disabled = false
format = '[$status]($style) '

[character]
error_symbol = '[>](bold red)'
success_symbol = '[>](bold yellow)'
vimcmd_symbol = '[>](bold yellow)'
