[manager]
hovered = { fg = "reset", bg = "#283457" }
preview_hovered = { fg = "reset", bg = "#283457" }
border_style  = { fg = "#27a1b9" }

count_copied = { fg = "green", reversed = true }
count_cut = { fg = "red", reversed = true }
count_selected = { fg = "yellow", reversed = true }

[mode]
normal_main = { fg = "#1a1b26", bg = "blue", bold = true }
normal_alt  = { fg = "blue", bg = "darkgray" }

select_main = { fg = "#1a1b26", bg = "magenta", bold = true }
select_alt  = { fg = "magenta", bg = "darkgray" }

[status]
sep_left  = { open = "", close = "" }
sep_right = { open = "", close = "" }

[icon]
conds = [
	# Special files
	{ if = "orphan", text = "" },
	{ if = "link", text = "" },
	{ if = "block", text = "" },
	{ if = "char", text = "" },
	{ if = "fifo", text = "" },
	{ if = "sock", text = "" },
	{ if = "sticky", text = "" },
	{ if = "dummy", text = "" },

	# Fallback
	{ if = "dir", text = "" },
	{ if = "exec", text = "" },
	{ if = "!dir", text = "󰈔" },
]
