language=es
layout=modern-compact

osc_on_start=bottom
window_controls=no

chapter_skip_buttons=yes
volume_control_type=logarithmic
hide_empty_playlist_button=yes
download_button=no
ontop_button=no
speed_button_click=0.25
speed_button_scroll=0.1
info_button=no

hover_effect=glow,color,box