name = "commands"
name_pretty = "Commands"
icon = "utilities-terminal-symbolic"
action = "%VALUE%"

[[entries]]
text = "Luz nocturna"
icon = "night-light-symbolic"
value = "pkill sunsetr || sunsetr"

[[entries]]
text = "Apagar"
icon = "system-shutdown-symbolic"
value = "systemctl poweroff"

[[entries]]
text = "Reiniciar"
icon = "system-reboot-symbolic"
value = "systemctl reboot"

[[entries]]
text = "Suspender"
icon = "media-playback-pause-symbolic"
value = "systemctl suspend"

[[entries]]
text = "Cerrar sesión"
icon = "application-exit-symbolic"
value = "loginctl terminate-user \"\""
